version: 0.2

env:
  variables:
    IMAGE_BASE_NAME: "swisstopo/service-alti"
    SHELL: "/bin/bash"
    AWS_DEFAULT_REGION: eu-central-1
    TEST_REPORT_DIR: "./tests/report"
    TEST_REPORT_FILE: "nose2-junit.xml"
  parameter-store:
    CI_DOCKERHUB_USER: "/dockerhub/user"
    CI_DOCKERHUB_PASSWORD: "/dockerhub/password"


phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Installing necessary softwares"
      - docker login -u ${CI_DOCKERHUB_USER} -p ${CI_DOCKERHUB_PASSWORD}
      - apt-get update && apt-get install -y docker-compose python3-pip

  pre_build:
    commands:
      - echo "Exporting of the image tag for building and pushing purposes"
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - GITHUB_BRANCH=${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/*}
      # Manual build don't have the CODEBUILD_WEBHOOK_HEAD_REF variable set, therefore use the source version set during the manual build
      - GITHUB_BRANCH=${GITHUB_BRANCH:-${CODEBUILD_SOURCE_VERSION}}
      - export IMAGE_TAG="${GITHUB_BRANCH}.${COMMIT_HASH}"
      - make clean setup

  build:
    commands:
      - echo Build started on $(date)
      - docker build -t ${IMAGE_BASE_NAME}:${IMAGE_TAG} .

  post_build:
    commands:
      - make lint
      - mkdir -p ${TEST_REPORT_DIR}
      - export TEST_REPORT_DIR=${TEST_REPORT_DIR}
      - export TEST_REPORT_FILE=${TEST_REPORT_FILE}
      - make test
      - docker push ${IMAGE_BASE_NAME}:${IMAGE_TAG}
      - echo Build completed on $(date)

reports:
  nose2_reports:
    files:
      - ${TEST_REPORT_FILE}
    base-directory: ${TEST_REPORT_DIR}
    file-format: JunitXml