version: 0.2

env:
  variables:
    IMAGE_BASE_NAME: "swisstopo/service-alti"
    SHELL: "/bin/bash"
    AWS_DEFAULT_REGION: eu-central-1
    TEST_REPORT_DIR: "./tests/report"
    TEST_REPORT_FILE: "nose2-junit.xml"
  parameter-store:
    CI_DOCKERHUB_USER: "/dockerhub/user"
    CI_DOCKERHUB_PASSWORD: "/dockerhub/password"


phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Installing necessary softwares"
      - docker login -u ${CI_DOCKERHUB_USER} -p ${CI_DOCKERHUB_PASSWORD}
      - apt-get update && apt-get install -y docker-compose python3-pip

  pre_build:
    commands:
      - echo "Exporting of the image tag for building and pushing purposes"
      # Reading git branch (the utility in the deploy script is unable to read it automatically on CodeBuild)
      # see https://stackoverflow.com/questions/47657423/get-github-git-branch-for-aws-codebuild
      - export GITHUB_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
      - |
        if [ "${GITHUB_BRANCH}" = "" ] ; then
          GITHUB_BRANCH="$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }')";
          export GITHUB_BRANCH=${GITHUB_BRANCH#remotes/origin/};
        fi
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG="${GITHUB_BRANCH}.${COMMIT_HASH}"
      - echo "GITHUB_BRANCH=${GITHUB_BRANCH} COMMIT_HASH=${COMMIT_HASH} IMAGE_TAG=${IMAGE_TAG}"
      - make clean setup

  build:
    commands:
      - echo Build started on $(date)
      - export DOCKER_IMG_TAG=${IMAGE_BASE_NAME}:${IMAGE_TAG}
      - echo "Building docker image with tag ${DOCKER_IMG_TAG}"
      - docker build -t ${DOCKER_IMG_TAG} .

  post_build:
    commands:
      - make lint
      - mkdir -p ${TEST_REPORT_DIR}
      - export TEST_REPORT_DIR=${TEST_REPORT_DIR}
      - export TEST_REPORT_FILE=${TEST_REPORT_FILE}
      - make test
      # Only push image to dockerhub for merge to develop and master
      - |
        if [ "${GITHUB_BRANCH}" = "master" -o "${GITHUB_BRANCH}" = "develop" ]; then
          docker push ${DOCKER_IMG_TAG}
        fi
      - echo Build completed on $(date)

reports:
  nose2_reports:
    files:
      - ${TEST_REPORT_FILE}
    base-directory: ${TEST_REPORT_DIR}
    file-format: JunitXml